//! Visualization helpers (PyMOL script generation placeholder)

use std::fs::File;
use std::io::{Result, Write};
use std::path::Path;

pub fn write_pymol_script(path: &Path, pocket_count: usize) -> Result<()> {
    let mut f = File::create(path)?;
    writeln!(f, "# PyMOL script generated by PRISM-LBS")?;
    writeln!(f, "bg_color white")?;
    for i in 0..pocket_count {
        writeln!(
            f,
            "set_color pocket{}, [1.0, 0.5, {}]",
            i + 1,
            (i % 10) as f64 / 10.0
        )?;
    }
    Ok(())
}
